const EV_STORAGE_CONNECTED = 'EV_STORAGE_CONNECTED'
const CRAWL_MODE = 'CRAWL_MODE'
const QUEUE_FINISHED = 'QUEUE_FINISHED'
const LRU_CACHE_SIZE = 500

module.exports =  {
    LRU_CACHE_SIZE,
    QUEUE_FINISHED,
    EV_STORAGE_CONNECTED,
    CRAWL_MODE,
    URI:{
        STATUS_UNCRAWLED:0,
        STATUS_CRAWLED:100,
    }
}
